config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  resources :pages
  resources :categories
  resources :images

  resource :help_doc, only: [:edit, :update] do
    get 'edit', on: :member, to: 'help_docs#edit'
    patch 'update', on: :member, to: 'help_docs#update'
  end

  resource :home, only: [:edit, :update] do
    get 'edit', on: :member, to: 'home#edit'
    patch 'update', on: :member, to: 'home#update'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :pages, dependent: :destroy

  def sorted_pages
    pages.sort_by {|page| page.title }
  end
end

app/models/help_doc.rb
class HelpDoc < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_help_text, only: [:new, :edit]

  private

  def get_help_text
    @help_doc_text = (HelpDoc.first or HelpDoc.new).help_text
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include UserHelper

  before_action :redirect_non_admin, except: :show
  before_action :find_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.order :name
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new category_params

    if Category.find_by name: category_params[:name]
      render_alert "Category #{category_params[:name]} exists."
    elsif category_params[:name].empty?
      render_alert 'Please supply a category name.'
    elsif @category.save
      redirect_to @category, notice: 'Category Created'
    else
      render_alert @category.errors.full_messages.to_sentence
    end
  end

  def update
    if category_params[:name].empty?
      render_alert 'Please supply a category name.', 'edit'
    else
      @category.attributes = category_params

      if @category.save
        redirect_to @category, notice: 'Category Updated'
      else
        render_alert @category.errors.full_messages.to_sentence, 'edit'
      end
    end
  end

  def destroy
    if @category.destroy
      redirect_to category_path, notice: 'Page Deleted'
    else
      render_alert @category.errors.full_messages.to_sentence, 'show'
    end
  end

  private

  def find_category
    @category = Category.find params[:id]
  end

  def render_alert message, view='new'
    flash[:alert] = message
    render view
  end

  def category_params
    params.require(:category).permit :name, :body
  end
end

app/controllers/help_docs_controller.rb
class HelpDocsController < ApplicationController
  include UserHelper

  before_action :redirect_non_admin

  def edit
    get_help_content
  end

  def update
    get_help_content
    @help_doc.attributes = help_doc_params.merge(id: HelpDoc.first.id)

    if @help_doc.save
      redirect_to root_path, notice: 'Help Text Updated'
    else
      flash[:alert] = @help_doc.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  private

  def get_help_content
    unless HelpDoc.first
      HelpDoc.new.save
    end

    @help_doc = HelpDoc.first
  end

  def help_doc_params
    params.require(:help_doc).permit :help_text
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include UserHelper

  before_action :redirect_non_admin, except: [ :index, :show ]

  def index
    show
    render :show
  end

  def show
    get_home_content
  end

  def edit
    get_home_content
  end

  def update
    get_home_content
    @home.attributes = home_params.merge(id: Home.first.id)

    if @home.save
      redirect_to root_path, notice: 'Page Updated'
    else
      flash[:alert] = @home.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  private

  def get_home_content
    unless Home.first
      Home.new.save
    end

    @home = Home.first
  end

  def home_params
    params.require(:home).permit :title, :body
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  include UserHelper

  before_action :redirect_non_admin

  def index
  end

  def new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include UserHelper

  before_action :redirect_non_admin, except: :show
  before_action :find_page, only: [:show, :edit, :update, :destroy]
  before_action :get_category_id, only: [:create, :update]
  before_action :category_selections, only: [:new, :edit, :update, :create]

  def index
    @pages = Page.all
  end

  def new
    if @category_selections.empty?
      redirect_to new_category_path, alert: 'Please create a category.'
    else
      @page = Page.new
      @category_name = nil
    end
  end

  def show
  end

  def edit
    @category_name = @page.category.name
  end

  def create
    @page = Page.new page_params.merge(category_id: @category_id)

    if Page.find_by title: page_params[:title]
      render_alert "Page #{page_params[:title]} exists."
    elsif page_params[:title].empty?
      render_alert 'Please supply a page title.'
    elsif @page.save
      redirect_to @page, notice: 'Page Created'
    else
      render_alert @page.errors.full_messages.to_sentence
    end
  end

  def update
    if page_params[:title].empty?
      render_alert 'Please supply a page title.', 'edit'
    else
      @page.attributes = page_params.merge(category_id: @category_id)

      if @page.save
        redirect_to @page, notice: 'Page Updated'
      else
        render_alert @page.errors.full_messages.to_sentence, 'edit'
      end
    end
  end

  def destroy
    if @page.destroy
      redirect_to pages_path, notice: 'Page Deleted'
    else
      render_alert @page.errors.full_messages.to_sentence, 'show'
    end
  end

  private

  def find_page
    @page = Page.find params[:id]
  end

  def page_params
    params.require(:page).permit :title, :body, :id
  end

  def find_category
    Category.find_by name: category_name
  end

  def create_category
    Category.new(name: category_name).save and find_category
  end

  def get_category_id
    @category_id = (find_category or create_category).id
  end

  def render_alert message, view='new'
    flash[:alert] = message
    render view
  end

  def category_name
    params[:page][:category]
  end

  def category_selections
    @category_selections = Category.order(:name).map do |category|
      [category.name, category.id]
    end
  end
end

app/helpers/application_helper.rb
require 'red_rug'

module ApplicationHelper
  def get_active_categories
    Category.order(:name).reject {|c| c.pages.empty? }
  end

  def markdown text
    # see RedRug documentation here:
    # http://fossrec.com/u/apotheon/redrug/index.cgi/home

    text ? RedRug.to_html(text).html_safe : nil
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
  def admin_signed_in?
    user_signed_in? and current_user.admin
  end

  def redirect_unauthorized
    flash[:alert] = 'You are not authorized to perform that action.'
    redirect_to root_path
  end

  def redirect_non_admin
    redirect_unauthorized unless admin_signed_in?
  end
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <div>
    <%= f.label :name, 'Category Name' %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.button 'Save Category' %>
  </div>
<% end %>

<div class="helpdocs"><%= markdown @help_doc_text %></div>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= render 'form' %>

app/views/categories/index.html.erb
<h2>Manage Categories</h2>

<ul>
  <% @categories.each do |category| %>
    <li><%= link_to "view #{category.name}", category_path(category) %></li>
  <% end %>
</ul>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h2>Create New Category</h2>

<%= render 'form' %>

app/views/categories/show.html.erb
<% if admin_signed_in? %>
  <%= link_to 'Edit Category', edit_category_path(@category) %>
  <%= link_to 'Delete Category', category_path(@category), method: :delete %>
<% end %>

<h2><%= @category.name %></h2>

<%= markdown @category.body %>

<ul>
  <% @category.sorted_pages.each do |page| %>
    <li><%= link_to page.title, page_path(page) %></li>
  <% end %>
</ul>

app/views/help_docs/edit.html.erb
<%= form_for @help_doc do |f| %>
  <div>
    <%= f.label :help_text, 'Help Text' %>
    <%= f.text_area :help_text %>
  </div>

  <div>
    <%= f.button 'Save Help Text' %>
  </div>
<% end %>

<div class="helpdocs"><%= markdown @help_doc_text %></div>

app/views/home/edit.html.erb
<%= form_for @home do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.button 'Save Homepage' %>
  </div>
<% end %>

<div class="helpdocs"><%= markdown @help_doc_text %></div>

app/views/home/show.html.erb
<% if admin_signed_in? %>
  <%= link_to 'Edit Homepage', edit_home_path %>
<% end %>

<h2><%= @home.title %></h2>

<%= markdown @home.body %>

app/views/images/index.html.erb
<h2>Manage Images</h2>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h2>Upload New Image</h2>

app/views/layouts/_header.html.erb
<div class="header">
  <ul>
    <li class="logo">
      <a href="/">
        <%= image_tag '/img/nrhs_logo.png', title: 'NRHS V-Twin Performance', alt: 'NRHS V-Twin Performance' %>
      </a>
    </li>

    <li class="nav header-nav">
      <%= link_to 'Where To Buy', '' %>
      <%= link_to 'Contact Us', '' %>
    </li>
  </ul>
</div>

app/views/layouts/_main_nav.html.erb
<nav class="nav main-nav">
  <ul class="nav-menus">
    <% get_active_categories.each do |category| %>
      <li>
        <%= link_to category.name, category_path(category) %>
        <ul>
          <% category.sorted_pages.each do |page| %>
            <li><%= link_to page.title, page_path(page) %></li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NRHS V-Twin Performance</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/main_nav' %>

    <div class="flash-messages">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <div class="content">
      <%= yield %>
    </div>

    <div class="nav main-nav">
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to 'Account Settings', edit_user_registration_path, :method => :get %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>

        <% if admin_signed_in? %>
          <li><%= link_to 'Manage Pages', pages_path %></li>
          <li><%= link_to 'Manage Categories', categories_path %></li>
          <li><%= link_to 'Manage Images', images_path %></li>
          <li><%= link_to 'Edit Help Text', edit_help_doc_path %></li>
        <% end %>
      </ul>
    </div>

    <div class="banner">
      <a href="http://www.xlbuellforum.com/">
        <%= image_tag '/img/xlbuellforum.png', title: 'XLBuellForum.com', alt: 'XLBuellForum.com' %>
      </a>
    </div>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for @page do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :category %>
    <%= f.select :category do %>
      <% @category_selections.each do |category| %>
        <%= content_tag :option, category.first %>
      <% end %>
    <% end %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.button 'Save Page' %>
  </div>
<% end %>

<div class="helpdocs"><%= markdown @help_doc_text %></div>

app/views/pages/edit.html.erb
<h2>Edit Page</h2>

<%= render 'form' %>

app/views/pages/index.html.erb
<h2>Manage Pages</h2>

<ul>
  <% @pages.each do |page| %>
    <li><%= link_to page.title, page_path(page) %></li>
  <% end %>
</ul>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h2>Create New Page</h2>

<%= render 'form' %>

app/views/pages/show.html.erb
<% if admin_signed_in? %>
  <%= link_to 'Edit Page', edit_page_path(@page) %>
  <%= link_to 'Delete Page', page_path(@page), method: :delete %>
<% end %>

<h2><%= @page.title %></h2>

<%= markdown @page.body %>